# Generated by Django 2.2.2 on 2019-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='potHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
                ('inchesDeep', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
