# Generated by Django 2.2.2 on 2019-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potHole', '0002_auto_20190622_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='inches_Deep',
            new_name='inches_deep',
        ),
        migrations.AddField(
            model_name='pothole',
            name='inches_wide',
            field=models.IntegerField(default=0),
        ),
    ]
