# Generated by Django 2.2.2 on 2019-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potHole', '0003_auto_20190622_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='message_text',
            field=models.CharField(default='Message', max_length=300),
        ),
    ]
