# Generated by Django 2.2.2 on 2019-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potHole', '0004_pothole_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
